# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180503_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_front_images',
            new_name='goods_front_image',
        ),
    ]
